import { dataSourceMap } from "@/lib/data-source-map";
import { roadmap } from "@/lib/roadmap";
import type {
  CompetitorPost,
  ContentPost,
  EventContext,
  ExperimentLogEntry,
} from "@/lib/types";

export const activeEvent: EventContext = {
  id: "gainesville-2026",
  name: "Amalie Motor Oil NHRA Gatornationals",
  track: "Gainesville Raceway",
  location: "Gainesville, Florida",
  dateRange: "Mar 20-23, 2026",
  stage: "eliminations",
  classes: ["Top Fuel", "Funny Car", "Pro Stock", "Pro Stock Motorcycle"],
  headline: "Fast-changing eliminations with upset potential and sponsor-heavy finish-line moments.",
};

export const ownedPosts: ContentPost[] = [
  {
    id: "nhra-1",
    platform: "instagram",
    account: "@nhra",
    createdAt: "2026-03-19T13:20:00Z",
    headline: "Force-style launch shakes the staging lanes",
    summary: "Tight vertical clip of launch reaction with a crew quote overlaid.",
    contentType: "behind-the-scenes",
    mediaFormat: "short-clip",
    publishWindow: "eliminations",
    driver: "Brittany Force",
    team: "John Force Racing",
    sponsor: "Monster Energy",
    eventId: activeEvent.id,
    tags: ["crew hustle", "hero run", "launch"],
    snapshot: {
      views: 238000,
      engagements: 22200,
      shares: 4100,
      saves: 3000,
      clicks: 1900,
      conversions: 160,
    },
  },
  {
    id: "nhra-2",
    platform: "youtube",
    account: "NHRA",
    createdAt: "2026-03-19T15:50:00Z",
    headline: "Three-round recap from the Gators",
    summary: "Edited highlight package with voiceover and sponsor slate.",
    contentType: "result",
    mediaFormat: "recap",
    publishWindow: "eliminations",
    driver: "Multi-class",
    team: "NHRA",
    sponsor: "Amalie",
    eventId: activeEvent.id,
    tags: ["roundup", "storyline stack", "sponsor payoff"],
    snapshot: {
      views: 91000,
      engagements: 6800,
      shares: 720,
      saves: 0,
      clicks: 2500,
      conversions: 210,
      watchTimeMinutes: 4200,
    },
  },
  {
    id: "nhra-3",
    platform: "facebook",
    account: "NHRA",
    createdAt: "2026-03-19T12:05:00Z",
    headline: "Round two bracket graphic",
    summary: "Static visual with ladder context and standout pairing callouts.",
    contentType: "result",
    mediaFormat: "static",
    publishWindow: "eliminations",
    driver: "Multi-class",
    team: "NHRA",
    sponsor: "Summit Racing",
    eventId: activeEvent.id,
    tags: ["bracket", "shareable", "quick hit"],
    snapshot: {
      views: 118000,
      engagements: 9700,
      shares: 3600,
      saves: 600,
      clicks: 1100,
      conversions: 95,
    },
  },
  {
    id: "nhra-4",
    platform: "instagram",
    account: "@nhra",
    createdAt: "2026-03-19T17:10:00Z",
    headline: "What changed on that record pass?",
    summary: "Explainer clip on track temp, tune-up, and reaction time.",
    contentType: "explainer",
    mediaFormat: "short-clip",
    publishWindow: "qualifying",
    driver: "Austin Prock",
    team: "John Force Racing",
    sponsor: "Cornwell Tools",
    eventId: activeEvent.id,
    tags: ["record chase", "education", "replay"],
    snapshot: {
      views: 176000,
      engagements: 15400,
      shares: 2400,
      saves: 2800,
      clicks: 900,
      conversions: 72,
    },
  },
  {
    id: "nhra-5",
    platform: "youtube",
    account: "NHRA",
    createdAt: "2026-03-18T22:15:00Z",
    headline: "Driver mic check before first qualifying hit",
    summary: "Short clip built around personality and anticipation.",
    contentType: "fan-reaction",
    mediaFormat: "short-clip",
    publishWindow: "pre-race",
    driver: "Antron Brown",
    team: "AB Motorsports",
    sponsor: "Matco Tools",
    eventId: activeEvent.id,
    tags: ["personality", "micd up", "hype"],
    snapshot: {
      views: 143000,
      engagements: 13200,
      shares: 950,
      saves: 0,
      clicks: 1300,
      conversions: 88,
      watchTimeMinutes: 3750,
    },
  },
];

export const competitorPosts: CompetitorPost[] = [
  {
    id: "comp-1",
    account: "@floridaraceweek",
    platform: "instagram",
    publishedAt: "2026-03-19T13:32:00Z",
    hook: "Winner circle in 12 seconds, no intro, just emotion.",
    mediaFormat: "short-clip",
    contentType: "fan-reaction",
    eventId: activeEvent.id,
    visibleEngagements: 16800,
    visibleViews: 132000,
    tags: ["crowd", "quick turnaround", "emotion"],
  },
  {
    id: "comp-2",
    account: "RacingTV",
    platform: "youtube",
    publishedAt: "2026-03-19T16:00:00Z",
    hook: "Full replay plus instant expert context on the upset lane.",
    mediaFormat: "recap",
    contentType: "upset",
    eventId: activeEvent.id,
    visibleEngagements: 5400,
    visibleViews: 64000,
    tags: ["analysis", "upset", "watch time"],
  },
  {
    id: "comp-3",
    account: "SpeedHub",
    platform: "facebook",
    publishedAt: "2026-03-19T12:18:00Z",
    hook: "Bracket card posted eight minutes after the round closed.",
    mediaFormat: "static",
    contentType: "result",
    eventId: activeEvent.id,
    visibleEngagements: 8200,
    visibleViews: 99000,
    tags: ["bracket", "speed", "shareable"],
  },
];

export const experimentLog: ExperimentLogEntry[] = [
  {
    id: "exp-1",
    hypothesis: "Driver-reaction clips during eliminations will outperform edited recaps on Instagram.",
    testWindow: "Gatornationals eliminations",
    result: "winning",
    learning: "Unfiltered emotion plus same-hour posting is currently the best Instagram package.",
  },
  {
    id: "exp-2",
    hypothesis: "YouTube recap packages with a visible bracket thesis will increase click-through to event coverage.",
    testWindow: "Race weekend daily recap",
    result: "promising",
    learning: "Recaps are converting, but the opening hook needs sharper contrast around upsets or records.",
  },
  {
    id: "exp-3",
    hypothesis: "Sponsor-forward graphics can perform if tied to a decisive result, not a generic promotional slate.",
    testWindow: "Finals sponsor test",
    result: "paused",
    learning: "Standalone sponsor creative underperformed compared with sponsor moments embedded inside racing stories.",
  },
];

export const appSeedData = {
  activeEvent,
  ownedPosts,
  competitorPosts,
  experimentLog,
  dataSourceMap,
  roadmap,
};
